create table px_projects2 (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , name_jtl      varchar2(500)   not null constraint px_projects2_name_tl_ck CHECK (name_jtl is json(strict))
  , description_jtl varchar2(4000) not null constraint px_projects2_desc_tl_ck CHECK (description_jtl is json(strict))
  , alias         varchar2(32)
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default 
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint px_projects2_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/

comment on table px_projects2 is 'List of projects';

comment on column px_projects2.name_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
comment on column px_projects2.description_jtl is 'JSON data with the language as keys. Syntax: [{"l": "us", "tl": "Project Analysis"}]';
comment on column px_projects2.active_ind is 'Is the record enabled Y/N?';
comment on column px_projects2.created_by is 'User that created this record';
comment on column px_projects2.created_on is 'Date the record was first created';
comment on column px_projects2.updated_by is 'User that last modified this record';
comment on column px_projects2.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger px_projects2_u
--------------------------------------------------------
create or replace trigger px_projects2_u
before update
on px_projects2
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
alter trigger px_projects2_u enable;
